### PR TITLE
statistic actions added

### PR DESCRIPTION
**Pull request by Fatema080136**
Without data provider as all the actions except two need different input. 
But if you need with data provider I can add.

### CODE REVIEW

**Comment by flashpixx** [comment]
assert in method ```exponentialselection``` and ```linearselection``` contains redundant information, checks for ```descriptive statistic``` are [missing and synchronization statistic objects](https://github.com/LightJason/AgentSpeak/blob/master/src/main/java/org/lightjason/agentspeak/action/buildin/math/statistic/CCreateStatistic.java#L116-L126) are missing, not [all possible statisic values](https://github.com/LightJason/AgentSpeak/blob/master/src/main/java/org/lightjason/agentspeak/action/buildin/math/statistic/EStatisticValue.java#L74-L111) are tested

**Comment by flashpixx** [comment]
remove redundant condition check, split test for selection and check the test result of selection

**Comment by Fatema080136** [comment]
In TestCActionGeneric.java and  TestCActionGenericType.java, I did not change anything. I just delete those files from my version as they where showing errors. In the end of my work, I added them again.

**Comment by flashpixx** [comment]
Please fix generic warnings in test-class, remove static properties, don't test linear-selection model with zero values, sometimes exponential-test is failing, so create a stable test-case, fix class naming convention, manual deletion of TestCActionGenericType class and TestCActionGeneric creates incorrect test-cases (Asserts are missing), compare it to the origin master branch and a correct fix / merge is mandatory

**Comment by Fatema080136** [comment]
The result of the selection test is unpredictable based on the weight. I could not think any other ways to test the result of this two functions. I compare TestCActionGenericType class and TestCActionGeneric  functions with:
https://github.com/LightJason/AgentSpeak/blob/master/src/test/java/org/lightjason/agentspeak/action/buildin/TestCActionGenericType.java
https://github.com/LightJason/AgentSpeak/blob/master/src/test/java/org/lightjason/agentspeak/action/buildin/TestCActionGeneric.java
If still have some problems, please let me know, I will try to fix.

**Comment by flashpixx** [comment]
selection-test should use a stable test-case, which can run everytime with valid input, so create a predictable test-case

**Comment by Fatema080136** [comment]
Sorry, I do not know, how to do that.

**Comment by flashpixx** [comment]
take a loot into the linear-selection and build a statical experiment with multiple runs

**Pull request merged**
