### PR TITLE
missing test functions of bitvector

### PR DESCRIPTION
**Pull request by Fatema080136**
I do not understand ToBlas function completely that is why do not know that the resulted value is correct or not.

### CODE REVIEW

**Comment by flashpixx** [comment]
Please finish the test entirely, for details take a look on the documentation of COLT https://dst.lbl.gov/ACSSoftware/colt/api/overview-summary.html

The calls do only converting the data types

**Comment by Fatema080136** [comment]
I have seen the documentation. Did not find toBlas in bitVector package. I understood that it coverts vector to doublematrix1D and it works perfectly. One thing I could not understand is that how {false, true, true} (vector) is converted to -7.0 (doublematrix1D).

**Comment by flashpixx** [comment]
```elements``` returns the decimal definition of the bit sequence, but I have changed in the commit  f1f0f66d605cad02dde7388b8b513c0c8ef7d98b the results of ```toBlas``` so that the method has the correct behaviour

**Comment by flashpixx** [comment]
I have added ```toBlas``` also to the matrix package because auf uniformity

**Pull request merged**
