### PR TITLE
Matrixbit

### PR DESCRIPTION
**Pull request by Fatema080136**

### CODE REVIEW

**Comment by flashpixx** [comment]
The tests are failing:

```
TestCActionBitMatrix.singleinputaction:196 array lengths differed, expected.length=0 actual.length=1
TestCActionBitMatrix.singleinputaction:196 array lengths differed, expected.length=1 actual.length=0
```

and multiple ```Assert.assertEquals``` calls uses for comparing different object types ```BitMatrix != BitVector```

**Comment by flashpixx** [comment]
Asserts comparison are still wrong

**Comment by Fatema080136** [comment]
Only In row and column functions, Assert.assertEquals calls uses for comparing results with BitVector, as these functions return BitVector. I simplified two test cases to one, as it do not need two test cases.  Which sources are not up to date?

**Comment by flashpixx** [comment]
> Am 23.04.2017 um 12:05 schrieb Fatema Tuj Johora <notifications@github.com>:
> 
> Only In row and column functions, Assert.assertEquals calls uses for comparing results with BitVector, as these functions return BitVector. I simplified two test cases to one, as it do not need two test cases.
> 
There are 4 wrong assert comparison
> Which sources are not up to date?
> 
You are 2 commits behind the master in your branches.

Phil

**Comment by flashpixx** [comment]
some asserts comparison  are still wrong

**Comment by flashpixx** [comment]
The coverage of the vector test are at ~70%
https://lightjason.github.io/AgentSpeak/cobertura/frame-summary-org.lightjason.agentspeak.action.buildin.math.bit.vector.html

some test-cases are incomplete

**Pull request merged**
